# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: Hack me
# Никнейм в Telegram
author: "@ColdKrevedKO"
# Описание таска на платформе.
description: |
    `@ColdKrevedKO`

    Объект SCP-647 известен тем, что поедает... Всякое.
    Удивительно, но в этот раз данный объект показал свою склонность к ... Кликам?
    Накормите голодную коробочку.


# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: forensic
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{h3ll0_h4ck3rm4n}"
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
 - public/ClickMe.exe

# Подсказки. Можно передавать словари и строки
hints:
  - {
      content: "Удачи в реверсе Qt, а я чем-нибудь еще позанимаюсь. А если серьезно, то задачка не просто так в форензике лежит.",
      cost: 20
    }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"