# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: Linear state
# Никнейм в Telegram
author: "@NikitaBerezhnov"
# Описание таска на платформе.
description: >
    `@NikitaBerezhnov`

     Оперативники из отряда Длани Белой Змеи измеряли показания объекта SCP-2424. К сожалению, показания прибора сбились.
     Нужно срочно восстановить его состояние, иначе все данные исследования будут потеряны.



# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: crypto
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{be5t_l1near_br7te_s0lv5r}",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
 - public/encrypt.py

# Подсказки. Можно передавать словари и строки
hints:
   #  - {
   #      content: "Попробуйте использовать steghide",
   #      cost: 10
 #    }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"