# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: 'Admin console #1'
# Никнейм в Telegram
author: "@devijoe"
# Описание таска на платформе.
description: |
    `@devijoe`

    Объект класса SCP-888 представляет из себя непонятную платформу, умело маскирующуюся под обычную админ-панель.  
    Для ее обслуживания, согласно Протоколу Комитета по исследованию особо опасных админ панелей за номером 1.2-56ГК54
    было предложено приставить к ней специально обученного трубокладчика.

    На объекте проведено около 34 испытаний. Протокол испытаний: [ЗАСЕКРЕЧЕНО]. Результат испытаний: 
    большинство подопытных при виде админ-панели теряли дар речи и пытались взломать ее при помощи практик script-kiddy.
    Эксперимент остановлен в связи с угрозой существования SCP-888

# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: web
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
connection_info: https://admin.vrnctf.ru

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{000h_3nv_m4573r_53mp44441}",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#  - public/server.py

# Подсказки. Можно передавать словари и строки
hints:
    - {
        content: "Всегда можно попробовать перебрать все возможные пути по словарям. Но иногда и GET запроса с ключом cmd будет достаточно",
        cost: 5
    }
#     - {
#         content: "Для создания пользователя они явно использовали команды оболочки.",
#         cost: 10
#     }
    # - Обратите внимание на хинт

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"