# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: Terror
# Никнейм в Telegram
author: "@kahiroomba"
# Описание таска на платформе.
description: |
  `@kahiroomba`

  Спустя долгое время, нам удалось вычислить и найти вневременную сущность объекта 584 “Туунбак”.
  Из-за него погибла экспедиция Франклина – бедные люди оставили записку ровно перед тем, как на них начали охоту.
  Для его локализации и удержания необходимо ввести в наше устройство код, в котором будут последние  координаты места, в которых с ним столкнулись и время (появление этой сущности останавливает механические часы).
  Достаточно будет двух координат и времени. Ищите – и, возможно, нам удастся спасти еще одну экспедицию!

  Формат флага:
  lat. 10˚ 10' S., long. 10˚ 10' W., время 1:1:1 будет представлено как
  vrnctf{10_10_S_10_10_W_1H_1M_1S}
# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: osint
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  # Нечувствительный к регистру флаг
  - {
    type: "static",
    content: "vrnctf{69_37_N_98_41_W_4H_1M_43S}",
    data: "case_insensitive",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/task.osz

# Подсказки. Можно передавать словари и строки
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
