# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: Yet another traffic dump
# Никнейм в Telegram
author: "@ColdKrevedKO"
# Описание таска на платформе.
description: |
    `@ColdKrevedKO`

    При очередной активации объекта SCP-1162-V наш анализатор траффика перехватил сигнал
    подозрительно похожий на траффик сети ZigBee.
    К сожалению, нам не удалось разобрать передаваемую информацию.
    Надеемся, что у Вас это получится.



# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: forensic
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{Z1gb33_4l14nc3_09}",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
 - public/yet_another_traffic_dump.pcapng

# Подсказки. Можно передавать словари и строки
hints:
     - {
         content: "Харкод - не хорошо, особенно в протоколе",
         cost: 10
     }
     - {
         content: "А что если выявить паттерн и убрать лишнее?",
         cost: 10
     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"