# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: Free server
# Никнейм в Telegram
author: "@wenzzer"
# Описание таска на платформе.
description: |
    `@wenzzer`

    ---

    > SBER - cпонсор данной задачи

    ---

    Всего неделю назад в одну из лабораторий наняли нового системного администратора, а он уже сошел с ума...
    Как-то странно это всё. Прошлый продержался целый месяц!
    То ли SCP-623 и SCP-475 стали последней каплей, то ли действительно работа нервная...
    В любом случае, пока не найдем нового администратора, присмотреть за сервером придется вам.

    А вот и сам сервер: scpLab.ova

    https://disk.yandex.ru/d/zgge_mm9KxQ8Fg

    Конечно же вам понадобятся учетные данные для входа:
    Login: scp
    Password: scp

    ---

    Прежде чем уйти на заслуженный отдых, админ заметил, что на сервере происходит что-то странное: то выполняются команды, то появляются и пропадают файлы.
    Похоже кто-то смог получить удаленный доступ до нашего сервера и закрепиться на нем или опять какой-то SCP выбрался на свободу?!



# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: forensic
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  - {
    type: "static",
    content: "vrnctf{Scp_1337_w3c_sh311}",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
files:
#  - public/flag.txt

# Подсказки. Можно передавать словари и строки
hints:
     - {
         content: "Похоже злоумышленник использовал какую-то из известных техник: https://attack.mitre.org/techniques/T1505/",
         cost: 10
     }
     - {
         content: "Мы же отключали веб-сервер... Что за чертовщина?",
         cost: 10
     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"