# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: Recruit
# Никнейм в Telegram
author: "@kahiroomba"
# Описание таска на платформе.
description: |
  `@kahiroomba`

  SCP-■■■■, представляющий собой ■■■■■■■■, позволяет собирать огромное количество информации о людях и обеспечивать массовую слежку. К сожалению, данным объектом завладела миланская компания ■■■■■■■ ■■■■, которая передавала полученные данные сторонним компаниям и агенствам.

  Нам требуется найти человека, которого можно завербовать и внедрить в данную компанию. С помощью объекта SCP-■■■■ мы получили огромный массив данных в котором содержаться несколько зацепок о возможном кандидате. Известно, что потенциальный рекрут данной компании участвовал в соревнованиях по информационной безопасности вместе с одним из сотрудников ■■■■■■■ ■■■■.

  Агент, выясните имя данного человека и название команды в которой они вместе выступали.

  Формат флага: vrnctf{Name_Surname_TeamName}

# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: osint
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  # Нечувствительный к регистру флаг
  - {
    type: "static",
    content: "vrnctf{Luca_Guerra_Guard@MyLan0}",
    data: "case_insensitive",
  }
  - {
    type: "static",
    content: "vrnctf{Luca_Guerra_ChocolateMakers}",
    data: "case_insensitive",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/task.osz

# Подсказки. Можно передавать словари и строки
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
